project:
  type: book
  output-dir: _book

book:
  title: "Nextcloud Test"
  author: "Author Name"
  date: today
  downloads: [pdf, epub]
  repo-url: https://github.com/mrchristian/nextcloud-test
  repo-actions: [edit, issue, source]
  site-url: https://mrchristian.github.io/nextcloud-test/
  chapters:
    - index.qmd
    - chapters/01-introduction.qmd
    - chapters/02-premises.qmd
    - chapters/03-project-design.qmd
    - chapters/04-implementation.qmd
    - chapters/05-long-term-perspective.qmd
    - chapters/06-planning-for-the-future.qmd
    - chapters/07-appendix.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: cover.png
  pdf:
    documentclass: scrreprt
    keep-tex: false
  epub:
    cover-image: cover.png
