# Premises: Key Considerations Before Starting Your DSE

D02 Basic premises

To do:

-   General: Check, if the references to the Appendix are right: Does the appendix have the promised information?

<!-- -->

-   [1.2.2 Institutions: give details on national support institutions other than Germany]{.mark} == this comes up at several places! If so: what countries/cultural-linguistic regions do we want to represent? In the group represented: France, Italy, Switzerland[]{.mark}

-   1.3.2 Link to DMP-section is still missing

-   Mareike: I proofread the chapter, harmonised, and corrected the English; I also added some comments. There still needs some work to be done on the bibliography. The linking to sources is not consistent.

-   == this chapter is clearly for those who want to create a DSE, not for students; I do not think it matters, but maybe we can add a remark somewhere.

-   I suggest adding a box at the end with "cited editions" (and do that throughout the book).

-   

This chapter introduces the basic concepts required to understand or embark on a digital scholarly edition. It explains the main principles of DSEs: a (collaborative) endeavour that requires a combination of areas of expertise aiming to address a range of scholarly, technical, legal and ethical issues. The FAIR principles -- Findability, Accessibility, Interoperability, and Reusability -- are crucial for the long-term usability of any edition.

**Keywords**

Keyword 1: Project design

Keyword2: Collaboration

Keyword3: Source selection

Keyword4: Data management plan

Keyword5: Research ethics

+-----------------------------------------------------------------------+
| **⚙️ Technologies**                                                   |
|                                                                       |
| -   Project management tools: boards, shared calendars, GANTT         |
|                                                                       |
| -   Data Management Plan tool (DMP), e.g. RDMO                        |
|                                                                       |
| -   Zotero (state of the art-software for bibliography)               |
+=======================================================================+
+-----------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------------------------------------------+
| **🏛️ Support from 3rd parties (infrastructure)**                                                                                    |
|                                                                                                                                     |
| -   Helpesks in research infrastructure consortia on national or European level with focus on DSE (e.g. Text+ ConsultingIT support) |
|                                                                                                                                     |
| -   Digital Humanities community via ADHO, EADH or via scholarly associations on the national level                                 |
|                                                                                                                                     |
| -   Templates, examples and repositories for Data Management Plans (OPIDOR, RDMO)                                                   |
+=====================================================================================================================================+
+-------------------------------------------------------------------------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### **FAIR/CARE** {#faircare-ch02 .unnumbered}                                                                                                        |
|                                                                                                                                                       |
| Questions that need to be asked BEFORE starting an edition:                                                                                           |
|                                                                                                                                                       |
| -   Will I encounter copyright issues at any stage of my project?                                                                                     |
|                                                                                                                                                       |
| <!-- -->                                                                                                                                              |
|                                                                                                                                                       |
| -   Does my project imply too much work for the planned team?                                                                                         |
|                                                                                                                                                       |
| <!-- -->                                                                                                                                              |
|                                                                                                                                                       |
| -   Have ethical, legal, and data protection requirements been clearly identified? Is my project potentially harmful to an individual or a community? |
+=======================================================================================================================================================+
+-------------------------------------------------------------------------------------------------------------------------------------------------------+

+------------------------------------------------------------------------------------------+
| ### **📋 Checklist** {#checklist-ch02 .unnumbered}                                       |
|                                                                                          |
| -   Start with your sources and research questions: they will guide all your choices.    |
|                                                                                          |
| -   Stick to what is necessary to answer your research questions.                        |
|                                                                                          |
| -   Engage with the DH community to benefit from their experiences.                      |
|                                                                                          |
| -   Identify possible ethical and legal issues linked to your project at an early stage. |
+==========================================================================================+
+------------------------------------------------------------------------------------------+

**➚** CHAPTER: MAIN TITLE \<\<Link to another part in the document: use References \> Cross-reference\>\>

## Scope and Objectives of a Digital Scholarly Edition

This part presents key questions to consider when planning a digital scholarly edition. Before entering the planning phase, it is essential to define the scope of the project, e.g. determine sources and frame research objectives.

**Keywords**

Keyword1*:* Project design

Keyword2*:* Research questions

Keyword3: Source selection

Keyword4: Data reuse

### Primary Sources and Research Questions

Before thinking about a *digital* edition and how to move from a concept to its implementation, editors should identify their scholarly objectives. On top of helping make decisions, this will form the basis for any reporting required during the project.

While documentation can only be complete at the end of the project, documenting is a continuous activity that has to be initiated early on. Defining objectives is the first step towards a comprehensive documentation. This task can be implemented before the actual start of the project for example with the help of a Data Management Plan (DMP) tool ([➚]{.mark} **3.4. Structuring and Sustaining the Project.**)

When preparing a DSE, experience shows that it is particulary productive to ask the following questions:

1.  **Research questions:** What are the scholarly objectives of the project?

    a.  What do you want to investigate?

    b.  What do you need the information you provide in a digital form for?

    c.  What is the expected result of the project?

2.  **Primary sources:** What are the relevant sources?

    a.  Where are they located?

    b.  How accessible are they?

    c.  What is their format or medium (physical artefact, plain text, digitised image, transcription, annotation\...)?

3.  **Preparation:** Can you use the available sources as they are, or do you need to transform them (e.g. scanning, transcribing)?

These questions also form the basis for subsequent modelling decisions.

It is very tempting to go "all out" when designing an edition. But projects can differ in their aims and scope---consider for example a historical-critical edition of the complete works of an author vs. the edition of a "small", precisely framed corpus of historical sources---and this diversity is closely linked to the amount of resources needed, also financial. In order for a project to be successful, it is important to conceive it within the framework of the available resources. In theory, a DSE can always be expanded at a later stage. However, practice shows that most projects don't have the means (funding, people, time) to expand at a later stage. Moreover, a DSE is often a collaborative endeavour and during planning all experts in the team should work closely together.

The choice of source documents has a direct impact on the amount of preparatory work. If the material needs digitisation, librarians and other experts as well as existing (national) standards ([➚]{.mark} DFG Practical Guidelines on Digitisation) should be consulted. This includes the cataloguing process and creation of metadata. Additionally, transformation processes might be necessary, OCR and transcription as well as metadata mapping. XXXX HERE ADD TWO SENTENCES EXPLAINING HOW DATA AND METADATA RELATE TO THE DIGITIZATION PROCESS XXX

-   By assembling a corpus into a new dataset, it is possible to freely decide on its structure and preparation. The digitisation of objects and the assignment of the relevant metadata can or must be discussed, planned and carried out with the institutions that hold the materials. If collections of source documents are being catalogued and made accessible for the first time, this needs to be carefully assessed. It might take a while before a sufficient amount of high-quality data is actually usable in the context of a DSE.

-   Reusing data raises new questions: have the sources already been digitised, or only partially edited? What kinds of digital resources are available for reuse (digital version, online database, a digital scholarly edition, etc.)? Under what condition can they be reused (data format, accessibility, interfaces, etc.)? Reuse often requires adapting the data to fit specific research needs ([➚]{.mark} **5. Long Term Perspective on Your Edition** for further methods). It is also possible to combine data from previous projects, which typically implies data mapping. This can be time-consuming and requires specific skills. While standards can support this process, the specificity of individual projects often results in heterogeneous data models. These issues are discussed further in [➚]{.mark} **4.2. The Many Lives of the Data**, which focusses on data formats and standards.

### Learn From Existing Editions and Join the Community

Like many digital practices, DSEs are closely linked to the development of computing, with relevant literature dating back to the 1950s. DSEs build on the methodologies of "classical" scholarly editing as well as on established academic evaluation and reputation mechanisms.

Every digital scholarly edition builds on prior work. Its creators become part of a network of practitioners and can benefit from collective expertise. Exploring existing DSEs and identifying resources that can be reused can save newcomers time and effort. From existing editions, one can learn about different methods of data processing, observe a wide range of presentation formats, identify best practices, and become familiar with commonly used standards.

Keep in mind: It is possible to reuse not only data, but also editorial models, data models and sometimes even user interfaces. It is good practice for digital scholarly editions to publish their editorial guidelines. These can serve as valuable sources of inspiration when defining an editorial model. Previous editors may have encountered challenges that you are likely to face, and they have developed solutions to address them.

At the same time, it is necessary to adapt the editorial models of other DSEs to one's own project. This means following established editorial procedures, such as analysing primary sources, clarifying methods in accordance with the disciplinary field (for example in editorial philology, see the KONDE Weißbuch), and identifying the target audience (who is the edition addressing? who will use or reuse it?). These considerations help make appropriate adjustments to existing models.

Finally, do not forget to engage with the community. Researchers often rediscover features or approaches that have already been discussed for decades. There is a very active community of digital editors that can provide guidance when needed. Do not hesitate to join, even as a beginner or an observer ([➚]{.mark} **7.2. Appendix. Resources**).

## Doing It With the Right People

Creating a DSE requires a mixture of different skills (technical, editorial, in terms of content etc.). It also often relies on institutions providing infrastructures or services. The following helps you identify useful partners and connect your team with the large community of digital scholarly editors.

Keyword*s*

Keyword1*:* Support

Keyword2*:* Community

Keyword3*:* Team composition

### 1.2.1 Build Up Your Team According to Your Needs {#build-up-your-team-according-to-your-needs .unnumbered}

A DSE is a collective endeavour. To turn this general vision into a reality, an editor needs a team of allies with various, complementary skills. The team dedicated to a DSE can include IT staff, digital humanists or computer scientists contributing to the digital infrastructure (setting up servers, managing repositories, developing, installing, and maintaining software,\...) and researchers from various fields involved in the edition. Interdisciplinary work requires time and the collective effort of people with different backgrounds to understand each other. Collective work is also built on trust and respect, relying on the experience and advice of all team members.

Clarifying each team member's role helps individuals find their place within the overall setting. However, roles tend to change during the project's life time , especially as team members acquire new skills along the way. The composition of the team may also evolve over time, as new skill requirements emerge.

### 1.2.2. Institutions {#institutions .unnumbered}

In any project, data should not be stored solely on a personal computer, but on a *secure* repository like an institutional cloud. This ensures that data remains accessible, well organised, and reusable throughout the project, and facilitates its later publication in line with the FAIR principles. This applies not only to the editorial team creating the edition, but also to others who may be interested in its content. It is also good practice to keep data accessible even if no further work is carried out on the edition.[]{.mark}

In many countries, a DSE project can get support from research and memory institutions.[]{.mark}

**GLAM institutions**: Memory institutions are public or private organisations responsible for collecting, cataloguing, restoring, preserving and communicating cultural or historical objects. They are often referred to by the acronym GLAM for **G**alleries, **L**ibraries, **A**rchives and **M**useums. In the context of digital publishing, these institutions fulfil several missions: they offer valuable expertise in the field of creation and management of metadata; they guarantee (in most cases) the long-term preservation of data in the face of digital obsolescence; they can manage data storage; they have expertise in software independence, open formats and documentation; they can assign and maintain stable identifiers (DOI), etc. And last but not least, they can hold and preserve the original documents that are the subject of the edition.

In the [➚]{.mark} **7. Appendix**, you will find a list of relevant institutions.

**IT support units**: Universities generally have IT units responsible for supporting research activities. This support may, or may not, include the use and maintenance of digital tools as well as data modelling or structuring. IT support units play a crucial advisory role in selecting software solutions that comply with interoperability standards, and ensuring the best practices in data governance (such as personal data protection or backup procedures).

**DH professionals**: There are now also various DH labs or DH centres that specialise in digital editions (for example: Trier Center for Digital Humanities or DH University Berne). These units often oversee several projects (across one or more institutions) simultaneously. They generally offer their services on a fee basis.

**Rights holders (beneficiaries) and private collectors**: If the sources to be edited belong to private organisations or individuals, it is necessary to engage in a dialogue with them and formalise the terms of the partnership in the form of a contract.

Academic landscapes vary from one country to another. In general, institutions with permanent dedicated and qualified staff are a reliable source of support to implement editorial goals in a sound way and over time.

In **Germany**, many university libraries have established repositories to store research data. They can also support the long-term maintenance of an digital scholarly edition. Major Academies like the Akademie der Wissenschaften und Literatur Mainz (ADW), the Bayerische Akademie der Wissenschaften (BADW) or the Berlin-Brandenburgische Akademie der Wissenschaften (BBAW: Telota) have dedicated staff and infrastructure to maintain and preserve DSEs. As a first step, it is advisable to contact either the institution your project is located at or the institution which holds the material you wish to edit and find out which support they could offer. If your institution is unable to assist, ask for recommendations for other institutions.

In Italy:

In **Switzerland** the Swiss National Data and Service Center for Humanities (DaSCH) has existed for a few years. Its goal is to take care for the long term preservation of complex data and datasets. At present, there is no comprehensive solution for the long-term maintenance of digital scholarly editions. The best way is to get in contact with your university or institution first.

\[Should we say something about the difference between archiving the DSE data (i.e. XML files, scripts, images, metadata\] in a repository (for long-term safe keeping) and maintaining and preserving a DSE with its user interface, functionalities, databases, environments etc.? These are two very different scenarios and many institutions might say yes to one (data repository) but no to the other, so that self-hosting a DSE might be the only option for a researcher? Keep also in mind that not everyone who creates a DSE has a several-year funded project with a team, but might just be one person working a few hours per month on a several year, unfunded side project.\]

## Research Principles, Rights, and Ethics

This chapter briefly explains the FAIR principles. It also explains why legal and ethical issues should be carefully clarified in advance before publishing a DSE.

Keywords

Keyword1: Research ethics

Keyword2: FAIR principles

Keyword3: CARE principles

Keyword4: Licensing

### The FAIR Principles and Why They Matter

Well-documented data is key to its usability, in both the short and the long term. The FAIR principles provide a framework for improving data quality. There exist numerous resources on this topic (see [➚]{.mark} **Bibliography**); we present here the core ideas.

There are four FAIR principles defining data quality:

-   **F**indable. Basically, data that cannot be found cannot be used. To avoid this, rich metadata and unique, persistent identifiers are required.

-   **A**ccessible. Findable data is more likely to be used if it is accessible through open and standard protocols. Editors decide what to make publicly accessible---it does not necessarily have to be everything, but the conditions of access must be clearly defined and documented.

-   **I**nteroperable. If the edited data can be combined with other datasets, it is even more likely to be used! Open formats and standards, as well as shared vocabularies help to achieve this goal.

-   **R**eusable. For data to be reused or reproduced, those who did not produce it will need to understand how it was created in the first place. Thorough documentation of licensing, provenance, and quality is a good starting point.

These principles are meant to serve as a compass for editors, users, and reviewers of any digital publication.

### Rights and Licenses

Rights and licenses define the framework within which editions can be used and reused.

Intellectual property and copyright rules vary from country to country. Universities, more generally institutional legal departments, help you address these questions from the beginning. This may lead to a process of balancing openness and protection.

Editors should consider rights and licenses from the onset when gathering materials and sources. The information on rights and licenses will be included in the data management plan ([➚]{.mark} **3.4.2. The Data Management Plan**).

Often, original sources come with clear licensing information, especially when they are held by a memory institution; but for other material, additional research may be required to identify the right holder(s). You also have to check under which conditions it is possible to present the material in a digital edition, and clearly state any copyright restrictions and rights holders in the metadata. Establishing a formal agreement can help avoiding misunderstandings. If this is not possible, the legal situation in the country where the documents are archived or stored should be carefully examined.

In general, for all material created by the editorial team---transcriptions, annotations, translations, visualisations, etc.---we recommend following the "as open as possible, as closed as necessary" principle. This means publishing it under the most open license possible (like a Creative Commons Attribution 4.0 International License (CC-BY 4.0), see https://creativecommons.org/share-your-work/), while excluding only sensitive or copyrighted data.

Even if an edition contains copyright-restricted materials, the edition as a whole can still be published under a CC-BY 4.0 license. Metadata itself is generally considered to be in the public domain or are licensed explicitely under a No Rights Reserved License (CC0).

### Ethics

It is essential to determine, even before starting a project, whether the source data or materials raise ethical issues. The relevant information should then be included in the data management plan. Sensitive data, such as personal data, must be handled in accordance with the General Data Protection Regulation (GDPR). If applicable, check which parts of the data can be published and which need to be anonymised.

In some cases, it may be necessary to consult an ethics committee before initiating a scholarly digital edition. This is also relevant for data to which the CARE principles for Indigenous Data Governance (Collective benefit, Authority to control, Responsibility, Ethics) apply, e.g. when dealing with cultural heritage data from indigenous communities, minority groups or victims of wars or other atrocities. (see Chun et al. 2016, Smithies 2023).

It is adviseable to familiarise yourself with the applicable regulations concerning personal data of the country you're based in. For the European Union, the European Data Protection Regulation on handling personal data is codified in the GDPR. Be aware that there are different or no explicit regulations in other parts of the world. You may also contact the data protection officer (DPO), if such a position exists at your university.

## Bibliography

Editions cited in this chapter

[J. C. Lavater Online Briefedition](https://www.jclavater-briefwechsel.ch/about)

[Répbulique des Lettres](https://republique-des-lettres.ch/about/guidelines)

[Naegeli-Briefe.ch](https://naegeli-briefe.ch/home)

[Korrespondenzen der Frühromantik](https://briefe-der-romantik.de/)

Resources on the FAIR and CARE principles:

"FAIR Principles." Overview. https://www.go-fair.org/fair-principles/.

"A Guide to the FAIR Principles \| Openscience.Eu." July 7, 2025. https://openscience.eu/article/infrastructure/guide-fair-principles.

Jacobsen, Annika, Ricardo De Miranda Azevedo, Nick Juty, et al. "FAIR Principles: Interpretations and Implementation Considerations." *Data Intelligence* 2, nos. 1--2 (2020): 10--29. <https://doi.org/10.1162/dint_r_00024>.

Wilkinson, Mark D., Michel Dumontier, IJsbrand Jan Aalbersberg, et al. "The FAIR Guiding Principles for Scientific Data Management and Stewardship." *Scientific Data* 3, no. 1 (2016): 160018. <https://doi.org/10.1038/sdata.2016.18>.

[CARE principles for Indigenous Data Governance]()

Chun et al. 2016, Smithies 2023
