# Implementation

Digital scholarly editions are created in a process. The first part of this chapter covers the steps transforming a non-digital source into a digital object, which also includes the production of metadata and the online release of the edition, for example as a web application. The second part is devoted to formats for encoding your data. The focus is on texts as primary sources, but some hints to other objects are given in a dedicated section.

Keywords

Keyword1: Digitisation

Keyword2: Data Modelling

Keyword3: Visualisation

Keyword4: Workflow

Keyword5: Format

+----------------------------------------------------------------------------------------------------------------------------+
| **⚙️ Technologies**                                                                                                        |
|                                                                                                                            |
| DSE as digital products are based on a variety of technologies. The typical editing process involves the use of tools for: |
|                                                                                                                            |
| -   Text Recognition                                                                                                       |
|                                                                                                                            |
| -   Imaging                                                                                                                |
|                                                                                                                            |
| -   Encoding and Annotation                                                                                                |
|                                                                                                                            |
| -   Web Development                                                                                                        |
|                                                                                                                            |
| -   Editors like Oxygen XML Editor, LEAf-Writer, VSCode, XMLMind XML Editor                                                |
|                                                                                                                            |
| -   Open Refine for data reconciliation with external databases such as Wikidata or GND services                           |
|                                                                                                                            |
| -   Controlled vocabularies, authority files, ontologies                                                                   |
+============================================================================================================================+
+----------------------------------------------------------------------------------------------------------------------------+

+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **🏛️ Support from 3rd parties (infrastructure)**                                                                                                                 |
|                                                                                                                                                                  |
| -   National initiatives like Text+, DARIAH, \...                                                                                                                |
|                                                                                                                                                                  |
| -   Tools and Frameworks like TEIPublisher, Transkribus, eScriptorium, Pandore Toolbox, ediarum, EVT, \...                                                       |
|                                                                                                                                                                  |
| -   Collections of digitized sources that are provided by archives, libraries or national initiatives (for example in Switzerland: https://www.e-manuscripta.ch) |
|                                                                                                                                                                  |
| -   Library and IT services: for technical infrastructure and maintenance                                                                                        |
+==================================================================================================================================================================+
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------------------------------------------------------------+
| ### **FAIR/CARE**                                                                                                                                |
|                                                                                                                                                  |
| -   Make sure you choose universal standards so that your work is usable across platforms and software-independent (for example XML, HTML, \...) |
|                                                                                                                                                  |
| -   Let people know under which conditions your work can be reused (license)                                                                     |
|                                                                                                                                                  |
| -   Assign a unique identifier to your work so that it can be cited (for example a Digital Object Identifier (DOI))                              |
|                                                                                                                                                  |
| -   Whenever possible, publish all the software created during the research process (like scripts created for data processing)                   |
+==================================================================================================================================================+
+--------------------------------------------------------------------------------------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------------------------------------------------------------+
| ### **📋 Checklist**                                                                                                                             |
|                                                                                                                                                  |
| -   Make sure you have access to your primary sources, your objects of research and verify what you are allowed to do with the material[]{.mark} |
|                                                                                                                                                  |
| -   Learn which formats, technologies and platforms are best suited to your needs[]{.mark}                                                       |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Document your choices in terms of sources, licenses, editorial guidelines, data formats, and software stacks[]{.mark}                        |
|                                                                                                                                                  |
| <!-- -->                                                                                                                                         |
|                                                                                                                                                  |
| -   Declare the options for reusing your data[]{.mark}                                                                                           |
|                                                                                                                                                  |
| > []{.mark}                                                                                                                                      |
+==================================================================================================================================================+
+--------------------------------------------------------------------------------------------------------------------------------------------------+

Figure 4.1: Flowchart of the implementation process (mapping tools and formats to each step), image by the authors, CC BY 4.0.

##  From primary sources to digital data (4.1.)

### Collecting and digitising

Before beginning any work on a Digital Scholarly Edition (DSE), it is necessary to obtain the "edendum" (from Latin, roughly translatable as "that needs to be given or to be edited"), e.g., the core of the edition, the primary sources or their representations as digital documents (i.e. images). Such a corpus can be obtained by gathering and, if needed, digitising source documents. Items in different conservation conditions will come with different requirements. Some objects cannot be digitised, for instance manuscripts that are in such bad shape that they would fall apart if you tried to open them.[]{.mark}

Gathering your sources can be achieved in different ways.

The digital edition project can be done **in cooperation with a memory institution holding the objects**,. In that case, the gathering and digitising phases will usually happen at the same time, as the memory institution will probably digitisation in house, before sharing the collection with the rest of the DSE project team .

The digital edition project can also stem from the **request of private parties** who may provide funding themselves. In that case, the digitisation could be done by an external provider.

In a similar way, the digital edition could be **a one-person endeavour**, for example as part of a graduate or PhD thesis, and in that case, unless you have the funding or cooperate with a memory institution, you are responsible for the digitisation.

Finally, the last---and more convenient---option is that the **objects you want to edit are already digitised and available online**, as is the case, for example, with objects from the French National Library (BNF), as most of its holdings are available on the platform Gallica or with the holdings of the Norwegian National Library (NB) . This scenario will give the editor the opportunity to start working right away.

Is the collection on a platform hosted by a library, archive or similar institutions, and does it contain images? Then the editor has to ask the institution if a re-digitisation is needed (or possible). In some cases, only images from older digitisations are available. Modern digitisation efforts at memory institutions in Europe and many other places are done in accordance with international standards and with appropriate documentation of the technical and technological procedures. However, documentation might be difficult to find and smaller institutions, especially on the regional and local level might not have the infrastructure and knowledge required to adhere to international standards. Here, expect to only have digital images and basic metadata provided. The digitised material is created in accordance with international standards. Whether the editor has to procure digital imagesof the objects of their edition or has to outsource the digitisation, they have to make sure that the quality of the images and their metadata meets certain standards. Depending on the objects in question and the aim of the DSE, these may vary. Some funding agencies, like the German Research Foundation, have published practical guidelines for the digitisation of documents and other artifacts; others provide technical requirements in addition (see Altenhöner et al. 2023). When using digital images of documents and other media, make sure to credit the rights holder, for example the photographer or the memory institution, and check the licenses and available file formats. This information must be included in your data management plan ([➚]{.mark} **3.4.1. The DMP**) as well as in the information pertaining to data publication ([➚]{.mark} **2.3.2. Rights and Licences** ; [➚]{.mark} **5.2.2. Persistent identifiers**).

On this topic, see the training unit "Automatic Text Recognition -- where and how to get images": https://campus.dariah.eu/resources/hosted/automatic-text-recognition-atr-video-2-where-and-how-to-get-images

### Transcribing textual data

Having a digitised document is a good first step, but a digital scholarly edition requires human and machine-readable text. This section concerns itself primarily with the edition of textual documents and how to proceed when extracting machine-readable text from digital images.

Source documents can be handwritten, engraved, or printed and come in different languages, scripts, styles, formats and layouts. Think about documents that contain illustrations and ornaments, annotations in line or in the margins, or have been damaged or repurposed so that characters, words or even larger parts of texts are lost. These material features alongside the textneed to be made processable by a computer.

There are two approaches to transcription: Either you create the transcription manually, or by using software which performs automatic segmentation and text recognition on the digital images of your documents. When you decide whether manual or automatic transcription is more suitable, several aspects have to be taken into account: One aspect concerns the time spent on manual transcription versus using a tool for Automatic Text Recognition (ART) and correcting the output manually or even training -document or writer-specific text recognition models. The language and writing style of the documents in your edition can also be a tricky issue. While there are many powerful and highly accurate text recognition models for printed texts in most modern languages out there (you can use free or commercial Optical Character Recognition tools), the situation looks different when it comes to historical print and handwritten or engraved texts. Handwritten Text Recognition (HTR) has developed significantly in the past years, and we now have many HTR models available that transcribe documents with medium to high accuracy. This is especially true for historical European, Latin-based scripts and languages, but increasingly so for Arabic and other non-Latin scripts, too. In most cases, the automatically generated transcriptions need to be quality-checked and corrected by a human with the appropriate paleography and language skills, to be suitable for a DSE. There are several options available when doing ATR and their application depends on editorial needs, technical skills, and the types of documents that are processed. For printed documents with standard typography and layout, one, free option is to use Tesseract OCR, which works on a large number of modern scripts and languages. Running Tesseract OCR usually requires interacting with the command line,, however, it is available with a Graphical User Interface (GUI) inthe Pandore Toolbox. For documents with non-standard or heterogeneous scripts, or a mix of printed and handwritten text, the Transkribus platform for automatic text recognition can be useful. Working with the Transkribus platform is free, however, processing a larger amount of documents and/or using general, highly accurate, and fast HTR models requires a subscription.. Another widely used, free and open source text recognition instance is eScriptorium , powered by the Kraken OCR engine. eScriptorium has many open source HTR models for non-Latin scripts and non-European languages, especially Semitic languages.. Some commercial generative AI tools, like Mistral, are becoming better at text recognition for historical documents, too. Consider the ethical issues related to the use of generative AI before you embark on your journey. (see chapter 6). before doing so, see chapter 6 on ethical issues related to the use of AI). You can [check this ATR-tutorial to understand which option is the best for your project: https://www.adfontes.uzh.ch/tutorium/atr]{.mark}.

Some tools are conceived to support the manual transcription of digitised documents and some even support collaborative work in a virtual environment, for example ediarum for Oxygen XML editor, the Edition Visualisation Technology (EVT) for VSCode, Tacteo, or the TextGrid platform. It is also possible to use programming or web development environments like VSCode or GNOME Builder, or simply to produce a text file with your prefered editor.. The choice of platform, software and interface will have an impact on the data format and structure; therefore, the furthur steps of the workflow might differ. Version controlling, for example with Git, can assist workflow monitoring and collaboration.

Your editorial choices define how and what you transcribe and which tools to use. If you decide to create a diplomatic transcription, your aim is to render the text and the layout exactly as they are displayed in the primary source. While n a reading version of the edited text, you would normalise spelling and punctuation, and modernise the structure and layout of the text to best suit modern readers' expectations and habits.

Documenting your editorial guidelines, your use of automatic transcription tools and aids as well as the guidelines and practices of your human transcribers is considered good practice.

### Encoding textual data

Encoding textual data is a key step of a digital edition project. Text encoding consists of adding machine-readable information to a text in order to describe its structure, features of interest and your scholarly interpretation of it. These annotations can facilitate the analysis and increase the findability and reusability of the data. The annotation process involves adding semantic information to the text, which means that the markup does not only describe how a text looks, but also what its components represent.

Several technical approaches exist for encoding texts. In the humanities, the most widely adopted standard has been provided by the Text Encoding Initiative (TEI), alongside the related guidelines TEI-P5. For encoding musical notation in a machine-readable structure there is the Music Encoding Initiative (MEI), a community-driven, open-source effort whichs aims to provide an encoding system similar to the TEI. By using an established, widely used standard like TEI, your encoding will adhere to the FAIR principles (Calvo Tello et al. 2024). Furthermore, the TEI community offers teaching material and additional digital services on their website.

\[Insert a paragraph where you explain in simple terms that TEI is an XML schema; that it is a complex and extensive schema that tries to cover all kinds of textual phenomena and thus needs to be reduced and customised for your specific documents, scope, and aims of DSE. It is not adviseable to use the TEI in its entirety. Then you go over to "A customised XML schema reflects data modelling choices..." \]

Firstly, whether using TEI or not, it is useful to create an XML schema. An XML schema reflects data modelling choices. It predefines and formalises the organisation and content of an XML document. An XML schema a) helps you keep track of decisions and b) makes sure that an XML document is valid and well-formed by showing where there are mistakes based on the predefined annotation rules. There are a lot of openly available schemas for a variety of sources. If they do not meet all one's needs, it is possible to build upon them. Help with the development of a TEI/XML schema is provided by the ODD (One Document Does it all) specification.

One starting point for the encoding phase can be the choice of metadata, that is, data about your data or additional information about your object of study. In the TEI, metadata is grouped in the TEI header (\<teiHeader\>). This section is dedicated to the gathering of different types of information, such as details on the primary source and theelectronic file containing the edition, the editorial choices and the project in general. The level of detail depends on the goals of the edition, although some parts of the TEI header are mandatory. There is a dedicated section of the TEI guidelines specifying which parts of the TEI header are concerned: https://tei-c.org/release/doc/tei-p5-doc/en/html/HD.html.

It is important to adhere to the main structure of the original text, such as its division in chapters, paragraphs, stanzas etc., so that the digital edition reflects the organisation of the source document. In an interpretative transcription, an editor may decide to normalise certain word forms or to correct mistakes introduced during the writing process.

Another type of metadata to cover are named entities appearing in the source document such as persons, organisations, places and events. Keep in mind that there are different ways to annotate entities in your data, depending on the granularity you want to have. For example, a person may be tagged simply as \<person\>, but you could also be more specific and indicate other information on the name inside the TEI tag \<persName\>. The TEI guidelines provide many useful examples for encoding named entities.

Encoding named entiries and connecting them to authority files or other Linked Open Data (LOD) services, makes entities explicit and unequivocal. One German example for authority files would be the Gemeinsame Normdatei (translated as Integrated Authority File, short GND), provided by the German National Library, which is also popular in other German speaking countries. The Virtual International Authority File () is also widely used in Europe and the Americas when referencing a person or an organisationand is linked to many libraries across the world. Wikidata is another option and covers all kinds of named entities. For geographical names, like countries, cities, towns, or geographical regions GeoNames is most widely used.Country-specific options exist, e.g. the Swiss portal ortsnamen.ch which is dedicated to research on geographical names. All these resources are connected to one another.

Depending on the goals of a DSE project and the technical environment in which the data will be used, some rely on simplified XML schemas derived from the TEI, while others use formats such as [HyperText Markup Language]{.mark} (HTML), [JavaScript Object Notation]{.mark} (JSON) or [Resource Description Framework]{.mark} (RDF), particularly when interoperability with web technologies or linked data environments is required. In practice, many projects combine several formats: TEI to encode the text itself and other formats to publish, query, or connect the data with external resources ([➚]{.mark} **4.2. The many lives of the data**).

### Working with non-textual objects

Many editions contain non-textual material alongside text. There are also editions with a main focus on images, artworks, music, video or other cultural heritage objects. Although this book focuses on text as a research object, in this section we briefly present an example of non-textual digital editing, i.e., a music edition.

A music edition is a specific type of scholarly edition, with more and more examples using the Music Encoding Initiative (MEI) for encoding musical notation (Corpus Musicae Ottomanicae (CMO), Beethoven, etc.). In this way, music editions are similar to text editions and the MEI framework treats musical notation in the same way that the TEI treats text. They face similar problems in terms of transcription, structure and data modelling. Not all music editions annotate or publish audio data.

For annotating audio files, there is a variety of tools available. These annotations can be created and stored in a long-term usable format such as TEI-XML. Information about the audio file (identifiers and time stamps) would be encoded as metadata in the same TEI file. Independently from the front end (presentation layer) and back end (database, repository), the data can be reused and preserved in accordance with the FAIR principles.

An example of an edition of oral cultural heritage is Dengbêj Gazîn: Die Lieder einer Kurdin. It combines the recordings (audio files and some external Youtube video links) with the transcription and translation of the annotated song text. All textual material is provided in TEI and licensed with a Creative Commons Attribution 4.0 International License (CC BY 4.0), while the recordings stay copyright protected. The metadata refers to both the text and the audio file. An audio player was added to the web interface. The presentation layer is exchangeable.

## The Many Lives of the Data / Format Diversity

**Keywords :**

**Keyword1: [word processor]{.mark}**

**Keyword2:format**

**Keyword3:authority files**

**Keyword4:metadata**

**Keyword5: ontology**

**Keyword6: WYSIWYG**

Using multiple data formats can improve the reusability and interoperability of a digital scholarly edition, as different formats serve different purposes. Some formats are particularly interesting for long term preservation and usability, while others facilitate publication or data exchange. Designing a project in a modular way makes it possible to generate and maintain several formats from the same underlying data, ensuring that the edition remains usable across different platforms and over time. A landscape of formats and technologies with a scope of interoperability can be found on the German technology stack (Tech-Stack). Conversions from one format to another may be achieved using transformations, e.g using scripts or stylesheets, like [Extensible Stylesheet Language Transformations]{.mark} (XSLT), a language designed for transforming XML documents into other XML documents or other formats such as HTML for web pages, plain text, or XSL Formatting Objects (XSL-FO).

### Metadata formats

Metadata are data. To be precise, they are data describing data. Metadata need to be expressed in structured formats in order to be exchanged, harvested, understood and properly stored. They can be placed inside the data file or dataset, for example in a TEI header, or in a separate file.

Standards for metadata are regulated by ontologies. In computer and information science, ontologies are [a structured, machine-readable framework that formally defines concepts, properties, and the relationships within a specific domain]{.mark}. These ontologies often use so called controlled vocabularies, that is a standardised list of predefined terms used to organise, index, and retrieve information[. ]{.mark} Complex metadata systems involve several ontologies (see for example the system used by the [BNF](https://data.bnf.fr/semanticweb#Ancre3)). XX THIS PARAGRAPH IS QUITE ABSTRACT FOR PEOPLE WHO HAVE NO IDEA WHAT THIS IS ABOUT; AN EXAMPLE WOULD BE GOODXX

A common and widely used metadata standard is Dublin Core.. The Dublin Core standard is a universal recommendation for the description of documentary resources, based on a fairly simple ontology that draws on different vocabularies and different models and can be rendered in different formats.

Simple Dublin Core contains 15 fundamental elements; qualified Dublin Core has undergone additions that specify subcategories and include further recommendations for the use of particular controlled vocabularies. The Dublin Core standard is primarily a sort of checklist for producing a structured description of a collection or documentary resource, like books or manuscripts. Dublin Core metadata can be serialised in different ways, using different machine-readable formats or languages like RDF-XML, XML, or HTML-XHTML.

### Image formats in DSEs

The choice of image formats depends on your editorial needs and your financial, technical and project-specific possibilities. While the commonly used PDF (Portable Document Format) is very robust and and good for exchanging data. However, if you need to extract information, like text or image metadata from a PDF, you will need to transform it, for example by performing automatic text recognition.

Other common image formats are [Portable Network Graphic]{.mark} (PNG), [Joint Photographic Experts Group]{.mark} files (JPEG) and [Tagged Image File Format]{.mark} (TIFF). TIFF is a proprietary format , optimised for multiple-layer images. It provides high level contrast and quality and can be used as a compressed file (as a .zip file) to store and display several images in a single file.

JPEG and PNG are non-patented and non-proprietary formats. Usually, JPEG provides lighter images than PNG.PNG is a lossless format, which means that filtering and compression preserve all information from the original image. If you need very high quality images, you should choose PNG over JPEG.

The Wikipedia has a great article about the different image formats.

All image formats allow to add some metadata directly in the file. It can be useful to discuss with the archive that holds the original sources which metadata they wish to include.

Should there be many images requiring metadata enrichment, it is possible to use a script or a tool. These can usually be provided by institutional IT support.

To make images available online, they should be combined with the related metadata, connected with other online material and allowed for people to interact with them: to do so, some possibilities are offered by the International Image Interoperability Framework (IIIF: https://iiif.io/).

### The textual documents: Plain Text, DOCX/ODT, Markdown, LaTex, XML ALTO, XML PAGE

Once again, the best format is the format that suits the specific project and its goals best. \[And how is the reader of this handbook supposed to know what the best format is that suits their needs? You are supposed to tell them what format suits best which goal! Don't leave them hanging here. They have probably never heard of Markdown or XML ALTO, so how are they supposed to choose?\] Any decision will have consequences on the fairness and durability of the data. \[Yes, and that is why you need to provide them with the information to make that decision.\]

If there is no need for semantic annotations, it is possible to use plain text formats like TXT. It is a light, interoperable, open format with a very strong reliability, however, it poorly stores and represents structual information like highlighting, headings, or font changes.it should be compatible with a [word processor]{.mark}. A word processor is a software dedicated to the production of highly formatted documents, with a WYSIWYG (What You See Is What You Get) perspective.

DOCX is the format maintained by Microsoft for the Office suite. DOCX is a very elaborate format. It has been created to replace DOC in order to produce more interoperable files. Like for TIFF, a DOCX file is in fact a sort of container of multiple files. It relies on a specific and proprietary specification of XML, Open XML. For the same kind of service (styling and formatting), you can use instead LibreOffice and the ODT format.

Considering specific and complex formatting needs, for example when dealing with mathematical texts involving equations and similar elements, a more specialised format might be useful, such as Markdown and TeX , available with text editors or online platforms (such as Overleaf).

If you have used applications like Transkribus or eScriptorium for automatic text recognition, you will have the option to export the text with information about text and layout structure. Two common formats which contain specific layout and position information are ALTO XMLl and PAGE XML, which can be transformed into TEI compatible encoding. For platforms like Transkribus, you can also export TEI XML directly.

### Deployment and Visualisation: HTML with CSS, PDF, CSV, GIS

As pointed out in [Andrews and Van Zundert (2018)]{.mark}, the way you choose to visualise your edition is in itself a mirror of your interpretation of the primary sources. An editor's interface is their message to the users. The interface of a DSE is never neutral, just like all of the choices that are made in previous editorial steps about data modelling, encoding, and technology stack. The way texts are presented expresses editorial choices and interpretations.

To make an edition accessible to the public, one option is to store the files in a repository (see [➚ **7.**]{.mark} **[Appendix]{.mark}** for a list of infrastructures storing scholarly data), but in most cases, it is useful and expected display the data in a web interface. To do so, the encoded data should be transformed into formats that users can consult online. The most common frontend languages for websites are HTML, CSS and JavaScript. Making your edition accessible in this way also means providing an interface that allows for navigation, exploration and reuse. There are two principle ways to achieve this goal: using an existing digital edition framework or developing a custom interface from scratch (see [➚]{.mark} **[3.3.2]{.mark}** on planning for your **Interface design**).

Deploying an interface, application or website online means making the data accessible on a web server so that users can consult them via a browser. In a typical architecture, the data layer (for example TEI-XML files or a database such as PostgreSQL or eXist-db) stores the encoded texts and metadata, while the back end handles queries and data transformations. The front end is the web interface that displays content. The entire system is hosted on a server (institutional infrastructure, research platform, or cloud service, often at a cost ([➚]{.mark} **7. Appendix**) that delivers the website and ensures that the data and interface remain accessible online.

Here are some points to remember when deploying an edition online and keeping user experience in mind:

-   The interface should be easy to navigate through accessible menus

-   The interface should be as inclusive as possible [(➚**3.3.3 Accessibility**)]{.mark}

-   The interface should document the underlying methodology

-   The interface should display exactly what the editor planned for it to display

<!-- -->

-   It should include a feedback button or an easy contact form ([➚]{.mark} **5.2.3. Make your edition visible**)

-   Data should be easy to download (as PDF, CSV files or other formats), including the textual data, the metadata, images etc.,

-   Offering APIs is a plus

-   Licensing, credits and rights must be clearly stated

The choices made when encoding the source document enable the interface to present the data differently. For a textual edition, this can include using the annotations to generate indexes of persons, places or works, even maps based on geographic references (GIS, cf. Recogito), or visualisations of networks, timelines, as well as statistical distributions (cf. the DFHG project). These visualisations can be produced using common technologies such as QGIS, Python libraries (e.g. Pandas, Matplotlib) or interactive tools like Plotly. They empower users with the opportunity to explore patterns in the data and approach the corpus from new analytical perspectives.

##  Bibliography

Editions cited in this chapter

[Corpus Musicae Ottomanicae (CMO)](https://corpus-musicae-ottomanicae.de/content/index.xml?lang=en)

[Beethoven](https://beethovens-werkstatt.de/)

Dengbêj Gazîn: Die Lieder einer Kurdin

Resources and Literature

Altenhöner, Reinhard, Andreas Berger, Christian Bracht, et al. *DFG Practical Guidelines on Digitisation. Updated Version 2022.* February 16, 2023. https://doi.org/10.5281/ZENODO.7561148.

Andrews, Tara L., and Joris J. van Zundert. *What Are You Trying to Say? The Interface as an Integral Element of Argument*. Vol. 12, edited by Roman Bleier, Martina Bürgermeister, Helmut W. Klug, Frederike Neuber, and Gerlinde Schneider. BoD, 2018. <http://www.uni-koeln.de/>.

Bisson, Marie, Edith Cannet, Anne Goloubkoff, et al. "Modélisation Des Métadonnées En XML-TEI. Pratiques de l'IR Métopes et Du Pôle Document Numérique de La MRSH de Caen." October 2022. <https://hal.science/hal-03830903>.

Calvo Tello, José, Mathias Göbel, Ubbo Veentjer, Stefan E. Funk, Nanette Rißler-Pipka, and Keli Du. "FAIR Derived Data in TEI and Its Publication in the TextGrid Repository." *Journal of the Text Encoding Initiative* 18 (2024). https://doi.org/10.4000/13llz.

Candela, Gustavo, María Dolores Sáez, MPilar Escobar Esteban, and Manuel Marco-Such. "Reusing Digital Collections from GLAM Institutions." *Journal of Information Science* 48, no. 2 (2022): 251--67. https://doi.org/10.1177/0165551520950246.

Cugliana, Elisa. *Coding Editions. Computational Approaches to the Editing of Pre-Modern Texts.* March 10, 2023. https://doi.org/10.5281/ZENODO.7715284.

Cummings, James. "A World of Difference: Myths and Misconceptions about the TEI." *Digital Scholarship in the Humanities* 34 (December 2018). https://doi.org/10.1093/llc/fqy071.

Driscoll, Matthew James, and Elena Pierazzo. *Digital Scholarly Editing: Theories and Practices*. Open Book Publishers, 2016. https://doi.org/10.11647/obp.0095.

Kanerva, Jenna, Cassandra Ledins, Siiri Käpyaho, and Filip Ginter. "OCR Error Post-Correction with LLMs in Historical Documents: No Free Lunches." In *Proceedings of the Third Workshop on Resources and Representations for Under-Resourced Languages and Domains (RESOURCEFUL-2025)*, edited by Špela Arhar Holdt, Nikolai Ilinykh, Barbara Scalvini, Micaella Bruton, Iben Nyholm Debess, and Crina Madalina Tudor. University of Tartu Library, Estonia, 2025. https://aclanthology.org/2025.resourceful-1.8/.

Kuczera, Andreas. "TEI Beyond XML--Digital Scholarly Editions as Provenance Knowledge Graphs." *Graph Technologies in the Humanities---Proceedings 2020, CEUR Workshop Proceedings* 3110 (2020): 101. https://ceur-ws.org/Vol-3110/paper6.pdf

O'Sullivan, James, Michael Pidd, Sophie Whittle, Bridgette Wessels, Michael Kurzmeier, and Órla Murphy, eds. *Digital Editing and Publishing in the Twenty-First Century*. 1st ed. Scottish Universities Press, 2025. https://doi.org/10.62637/sup.GHST9020.

Roeder, Torsten, and Patrick Sahle. "Architekturen. Überblick über Software für Editionen." Winter School Digitale Editionen, 02.-01.03 2019. https://www.i-d-e.de/wp-content/uploads/2019/11/08_Architekturen.pdf.

Sahle, Patrick. *Digitale Editionsformen, Zum Umgang Mit Der Überlieferung Unter Den Bedingungen Des Medienwandels, 3 Bände*. n.d. https://www.i-d-e.de/publikationen/schriften/s7-9-digitale-editionsformen/.

Spadini, Elena. "Scholarly Editing and the Semantic Web." In *Quantitative Und Qualitative Analyseperspektiven Für Eine Digitale Briefforschung*, edited by Aline Deicke and Jochen Strobel. De Gruyter, 2025. <https://doi.org/doi:10.1515/9783111675732-003>.
