# Planning for the future

Abstract

When considering the future of DSEs, many questions arise: In which parts of the workflow is the integration of large language models meaningful and how can this integration be used with care and responsibility, especially regarding environmental issues? What are the plans for increasing and facilitating the reuse and the sustainability of DSEs? How can the dissemination of DSEs in a broader context be increased, not limited to academic researchers? And in general: What challenges and possibilities will DSEs face in the future?

Keywords

Keyword1 : LLM

Keyword2 : GLAMs

Keyword3 : environmental impact

Keyword4: teaching

+--------------------------------------------------------------------------------------------------+
| **⚙️ Technologies**                                                                              |
|                                                                                                  |
| Some text to describe the link between the technologies and the current part. Bullets like that: |
|                                                                                                  |
| -   LLMs                                                                                         |
|                                                                                                  |
| -   HTR                                                                                          |
|                                                                                                  |
| -   Gamification                                                                                 |
|                                                                                                  |
| -   Linked Open Data                                                                             |
|                                                                                                  |
| -   Semantic Web                                                                                 |
+==================================================================================================+
+--------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **🏛️ Support from third parties (infrastructure)**                                                                                                                          |
|                                                                                                                                                                             |
| -   GAMS (Austria): support for LLM use in digital editions (CLARIAH-AT)                                                                                                    |
|                                                                                                                                                                             |
| -   Text+ (Germany): A consortium of the NFDI providing services and consulting regarding text- and language based research data (Editions, lexical resources, collections) |
+=============================================================================================================================================================================+
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+-------------------------------------------------------------------------------------------------------------------------+
| ### **FAIR/CARE**                                                                                                       |
|                                                                                                                         |
| -   Use of AI: Be aware of bias, check data protection and copyrights, run local or use a smaller European model        |
|                                                                                                                         |
| -   Always think about Open Science : if you can find a useful free LLM, prioritize this.                               |
|                                                                                                                         |
| -   Think about your data : Don't submit it to LLM if you have any restriction on it, especially if its sensitive data. |
+=========================================================================================================================+
+-------------------------------------------------------------------------------------------------------------------------+

+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| ### **📋 Checklist**                                                                                                                                |
|                                                                                                                                                     |
| -   Think outside the box: Use GLAM-institutions to spread your edition                                                                             |
|                                                                                                                                                     |
| -   Don't be afraid of progress but use it with care: If you are thinking about using AI, also make sure to be aware of its restrictions and risks. |
|                                                                                                                                                     |
| <!-- -->                                                                                                                                            |
|                                                                                                                                                     |
| -   Don't limit yourself : DSE is not limited to historical documents                                                                               |
|                                                                                                                                                     |
| -   Respect data rights (especially but not only when using AI).                                                                                    |
+=====================================================================================================================================================+
+-----------------------------------------------------------------------------------------------------------------------------------------------------+

## Implementing Artificial Intelligence (AI) and Large Language Models (LLM) into DSEs

### Ideas and Methods for AI Use in DSEs

AI and especially LLMs are currently changing the world of work in various regards. Academia is not immune to the changes these developments bring about. Contributions in Digital Humanities projects, journals and conference show that the community is discussing the promises, challenges and issues that come with the use of AI and LLMs for Digital Humanities in broader terms, but also for DSEs in particular (Ries et al. 2025). Many of these works concern themselves with the comparison and validation of different LLMs for a specific (editorial) task or discussions of the human-in-the-loop, e.g., the integration of human input into the life-cycle of AI systems. Even though the results seem promising and may rise questions about the need of "classical" editorial work, yet the results are not reproducible and therefore difficult if not impossible to reuse for academic research (Hindermann et al. 2026).

In general, the integration of computational approaches in the editorial workflow is a recent trend that promises to introduce automation into the process, e.g. transcription phases which use pipelines for the automatic normalisation of text (Cugliana 2023). Nowadays, LLMs are also involved in post-Automatic Text Recognition (ATR) correction ((Kanerva et al. 2025), (Thomas, Gaizauskas, and Lu 2024), (Boros et al. 2024)), a time-consuming task when dealing with not-completely accurate recognition models. This may be observe for example with the creation of competition on LLM-Assisted Optical Character Recognition (OCR) Post-Correction for Historical Documents (see https://hipe-eval.github.io/HIPE-OCRepair-2026/). There have also been several attempts at automatic text markup, in which different LLMs were used with and/or against each other to cross-check the results. Further applications are Named Entity Recognition (NER) and commenting issues (Ries et al. 2025). However, it is clear that a "human in the loop" is always necessary (Pollin 2025).

Algorithms which are creating the outputs of (proprietary) LLMs still remain a black box. Commercial LLMs are the product of profit-oriented private companies. So, without good, sustainable open-source solutions, which are in development but still not finished, researches are giving away their research and their data sovereignty to private investors. On top of that, ethical concerns like the storage of and training with private user data, the exploitation of workers in the global south for training LLMs as well as the environmental impact of AI system, must be taken into account.

### Considering the Environmental issues 

Digital editions, like every digital product, need resources. In contrast to a printed book, to keep a digital edition available, a continuous maintenance also in form of running servers is required. Digital Editions that come with a highly interactive, dynamic website (as opposed to a static site) or which are based on AI-trained models have per se a bigger enviromental footprint. When creating and disseminating a digital edition, an editor should always consider whether their edition can be produced in a more static format. This may be relevant for sustainability on various levels. Some guidelines exist that can provide insights on this topic: see for example the Endings project (https://endings.uvic.ca/principles.html ), created as set of principals, which may be followed when a DSE is created. Additional recommendations are provided by the working group Greening DH of the German DH-Association DHd ( https://dhd-greening.github.io/)^.^

Additionally, using AIs and more particularly LLMs, as we suggested, has an environmental impact. For example, LLMs running on Central Processing Units (CPU) require a substantial consumption of energy. This also means higher electricity costs. Current research considers this costly footprint and looks into solutions for "making LLM serving more sustainable" (Ding and Shi, 2024), considering the risks and benefits of LLMs for the environment (Rillig et al, 2023).

With regard to current political discussion about the environmental balance of free enterprises and demands of increasing environmental taxes as well as the need for climate certificates, the question arises how long academic projects that are also in the need of resources can be kept out of this discussion. With the emerging climate crisis, the pressure to justify the "value" of (digital) humanist work may also expand to this aspect.

## Digital Editions in Other Contexts

### GLAMs (Galleries, Libraries, Archives and Museums) and DSE

At the moment DSEs are an important area of work for DH, both in research and teaching. It is striking that edition projects are predominantly carried out as autonomous projects by an academic editor or group of editors. Current research has demonstrated how collections held by GLAM institutions can serve as data for various research purposes (Candela et al. 2022) -- DSE is just one potential use case to consider. But only a few GLAM institutions (as HAB (Herzog August Bibliothek) Wolfenbüttel, Austrian National Library (Österreichische Nationalbibliothek or ÖNB), Zentralbibliothek Zürich, Deutsches Literaturarchiv Marbach (DLA) and others) are currently actively working on digital editions and preparing their own collections in this form. It is to be hoped that other institutions will see digital editions as an opportunity to communicate their collections to researchers and make them accessible to a wider audience. The challenge hereby lies in the funding situation, which is not the same in all countries. While the Deutsche Forschungsgemeinschaft (DFG) or German Research Foundation, for example, also funds GLAM projects, these institutions are not eligible to apply to the Swiss National Science Foundation. Unless they cooperate with an academic editorial team, they must find other forms of funding. DSEs are a good opportunity for all the GLAMs to get in touch and work together with researchers and, in principle, can easily be implemented as cooperation projects (see for example Klug et al. 2021).

### Valorising a DSE outside Academia

In order to valorise a DSE in other contexts it is important to also spread it outside the academic environment: especially for DSEs whose topic is about well-known authors or well-known works, it is possible to consider a future outside the universities. A way to do so is collaborating with public institutions (GLAM) (see above) which hold manuscripts or books and are willing to collaborate with a team of experts to create a digital edition ofmaterials they hold. In that way, once the edition is published, the cultural institution help to enlarge the range of users by involving their public: for example, the institution can display the digital edition beside the analogue document in the visitor's path by a touchscreen device or putting a QR code near it. There are some experiments done in this way, although they are still exceptions ^(^Lukas et al. 2023^)^ describe how an exhibition can be viewed as a digital edition in its own right): in Italy, for example, there is the LETS museum in Trieste which collaborated with an academic team to develop a digital edition of Umberto Saba's Canzoniere and displayed it on a touchscreen device in the visitor's path (Buzzoni et al. 2024). Another good example of a DSE used outside its original context is the critical edition of the correspondence of Friedrich Engels\' family (https://familie-engels-briefe.de/). The Engels House, a museum dedicated to Engels\' life, uses this edition to provide visitors with a readable version of the corpus. It guides them through the correspondence with the help of critical commentaries and annotations created during the research project ( https://mr.uni-wuppertal.de/dim/projekte/website-fuer-die-medienstation-im-engelshaus-wuppertal-brief-korrespondenz).

Another way to valorise DSEs could be to include them in teaching programs also in highschools. To achieve this, teachers should be trained in the correct use of DSEs to be sure that they will be able to use them in their classes. DSEs, thanks to their interactivity, can provide good training for deductive learning: for example, DSEs which provide lists of named entities connected to hyperlinks can be explored autonomously by students. In order to achieve this, it may also be useful to consider the conception and implementation of DSEs more in the training of future teachers in universities, hence better integrating DSEs in curricula.

Another interesting strategy to disseminate editorial work is to offer the users of a DSE the possibility to give a feedback about the edition: in this way, it is easier to find out the features and the parts to improve for the editors and also the users feel to be part of a community in which they can somehow contribute.

### Gamification of DSEs

In addition to collaborating with GLAM institutions, editorial research projects continually explore alternative approaches to the entire research process. This impacts various stages, including the presentation and critical analysis of the sources themselves. Gamification, which includes both the rendition of the editorial environment as a game and the representation of the research object in a game format, is a recent and interesting practice that can bridge the gap between philology, computer science and citizen science. The mechanism of shared tasks, for example, which is typical of videogames, could be incorporated in a digital space for digital editing (Saklofske 2017).

Video games may also be viewed as an alternative format for disseminating research results. For example *Hwaet! The Vercelli Book Saga*, a videogame for mobile phones based on the Vercelli Book (https://tesorodelduomovc.it/vercelli-book/) is an example how cultural heritage objects can be interpreted, explained and brought closer to the general public through an immersive experience. More examples are to be found in the final bibliography of this chapter.

### Semantic Web and DSE

With the help of Semantic Web Technologies, DSEs may "move from document-centric to data-centric editions" and thereby "shape the future of scholarly editions" (Spadini 2025). While many DSEs still focus on the presentation of text and documents, using Triple Stores and SPARQL Endpoint as well as encoding the data as RDF has the potential to federate and map data from different knowledge bases and query the data semantics. Especially regarding the application of computational approaches, making DSE data accessible in a machine readable and easy mappable format through RDF and Linked Open Data can prevent data silos and helps linking and combining different knowledge domains.

### Usage of Open Source Software 

The development and long-term accessibility of DSEs is increasingly dependent on the strategic use of open source software. Open source solutions offer transparency, adaptability, and community-driven innovation, all of which are essential for scholarly work that must remain verifiable and reproducible over time. Unlike proprietary systems, open source tools allow researchers to inspect, modify, and extend code according to evolving academic standards and technological requirements. This flexibility not only reduces dependency on commercial providers. Open source ecosystems also enable collaboration across institutions and disciplines by sharing infrastructures and standards that enhance interoperability. As digital editions continue to grow in complexity and scale, the adoption of open source software is key to ensure their sustainability, accessibility, and scholarly integrity. []{.mark}

## Bibliography

Editions cited in this chapter

<https://familie-engels-briefe.de/>

Resources and Literature

Boros, Emanuela, Maud Ehrmann, Matteo Romanello, Sven Najem-Meyer, and Frédéric Kaplan. "Post-Correction of Historical Text Transcripts with Large Language Models: An Exploratory Study." In *Proceedings of the 8th Joint SIGHUM Workshop on Computational Linguistics for Cultural Heritage, Social Sciences, Humanities and Literature (LaTeCH-CLfL 2024)*, edited by Yuri Bizzoni, Stefania Degaetano-Ortlieb, Anna Kazantseva, and Stan Szpakowicz. Association for Computational Linguistics, 2024. https://doi.org/10.18653/v1/2024.latechclfl-1.14.

Candela, Gustavo, María Dolores Sáez, MPilar Escobar Esteban, and Manuel Marco-Such. "Reusing Digital Collections from GLAM Institutions." *Journal of Information Science* 48, no. 2 (2022): 251--67. https://doi.org/10.1177/0165551520950246.

Cugliana, Elisa. *Coding Editions. Computational Approaches to the Editing of Pre-Modern Texts.* March 10, 2023. https://doi.org/10.5281/ZENODO.7715284.

Ding, Yi, and Tianyao Shi. "Sustainable LLM Serving: Environmental Implications, Challenges, and Opportunities : Invited Paper." *2024 IEEE 15th International Green and Sustainable Computing Conference (IGSC)*, November 2024, 37--38. https://doi.org/10.1109/IGSC64514.2024.00016.

Fullerton, Tracy. *Walden, a Game EDU*. *Games + Learning + Society Conference Proceedings*. September 18, 2022. https://escholarship.org/uc/item/9tn6053m.

Kanerva, Jenna, Cassandra Ledins, Siiri Käpyaho, and Filip Ginter. "OCR Error Post-Correction with LLMs in Historical Documents: No Free Lunches." In *Proceedings of the Third Workshop on Resources and Representations for Under-Resourced Languages and Domains (RESOURCEFUL-2025)*, edited by Špela Arhar Holdt, Nikolai Ilinykh, Barbara Scalvini, Micaella Bruton, Iben Nyholm Debess, and Crina Madalina Tudor. University of Tartu Library, Estonia, 2025. https://aclanthology.org/2025.resourceful-1.8/.

Lagarias, Antonios. "Colloque CHR 2024 : les LLM (large language models) au service des humanités numériques ?" *Humanités numériques*, no. 11 (juil 2025). <https://doi.org/10.4000/1498y>.

Hess, Jan. "Von OCR Und HTR Bis NER Und LLM: Zur (Teil-)Automatisierung Digitaler Editions- Und Transformationsprozesse." *Editio* 38, no. 1 (2024): 147--62. https://doi.org/10.1515/editio-2024-0009.

Hindermann, Maximilian, Sorin Marti, Anthea Alberto, et al. *RISE-UNIBAS/Humanities_data_benchmark*. Zenodo, released March 24, 2026. https://doi.org/10.5281/ZENODO.19204070.

Jones, Steven, and Neil Fraistat. "The MOO as an Arcade: Minimalism and Interpretive literary Games." *TEXT Technology* 13, no. 2 (2004): 19--26. https://texttechnology.humanities.mcmaster.ca/pdf/vol13_2_02.pdf

Lukas, Wolfgang, Dana Machwitz, and Bastian Politycki. "Pörtner & Wühr: Spuren Des Original-Ton-Hörspiels Zwischen Wuppertal Und München: Ein Versuch, Textgenese Und Produktionsästhetik Auszustellen." *Editio* 37, no. 1 (2023): 102--21. https://doi.org/10.1515/editio-2023-0007.

Pollin, Christopher, Franz Fischer, Patrick Sahle, Martina Scholger, and Georg Vogeler. "When It Was 2024 -- Generative AI in the Field of Digital Scholarly Editions." *Zeitschrift Für Digitale Geisteswissenschaften* 10 (2025). https://doi.org/10.17175/2025_008.

Ries, Thorsten, Tara Andrews, Lisa Rosendahl, et al. *Critical AI in Der Digitalen Editorik*. February 26, 2025. https://doi.org/10.5281/ZENODO.14943125.

Rillig, Matthias C., Marlene Ågerstrand, Mohan Bi, Kenneth A. Gould, and Uli Sauerland. "Risks and Benefits of Large Language Models for the Environment." *Environmental Science & Technology* 57, no. 9 (2023): 3464--66. https://doi.org/10.1021/acs.est.3c01106.

Saklofske, Jon, Nina Belojevic, Alex Christie, Sonja Sapach, John Simpson, and The INKE Research Team. "Gaming the Edition: Modelling Scholarly Editions through Videogame Frameworks." *Digital Literary Studies* 1, no. 1 (2016). https://doi.org/10.18113/P8dls1159703.

Thomas, Alan, Robert Gaizauskas, and Haiping Lu. "Leveraging LLMs for Post-OCR Correction of Historical Newspapers." In *Proceedings of the Third Workshop on Language Technologies for Historical and Ancient Languages (LT4HALA) @ LREC-COLING-2024*, edited by Rachele Sprugnoli and Marco Passarotti. ELRA and ICCL, 2024. https://aclanthology.org/2024.lt4hala-1.14/.

The Endings Project Team. "The Endings Project: The Endings Project \| Le Projet Endings." Accessed March 30, 2026. [https://endings.uvic.ca/](https://endings.uvic.ca/%5bpage%20file%20name%20will%20be%20inserted%20here%5d).
