#  Appendix

This appendix intends to be more than a mere list of resources. Each entry is introduced separately in order to provide context regarding purpose, status and potential use. Since the appendix is intrinsically linked to the contents of this handbook, however, it does not claim to be exhaustive, but to shed light on the information provided in the other chapters.\
Please feel free to contribute resources that you find should be integrated.

## Selection of DSE projects/profiles/platforms

DiScholEd - Digital Scholarly Editions https://discholed.huma-num.fr/exist/apps/discholed/index.html []{.mark}

> This platform, created with TEI Publisher, has been developed as part of the DAHN project, a partnership between Inria, the University of Le Mans and the EHESS funded by the French Ministry of Higher Education and Research. Its goal is to establish a pipeline for the scientific digital edition of archival collections. It is hosted on Huma-num and offers seven collections, from a WWI correspondence to Holocaust Testimonies, from Berlin Intellectuals to a French poet.[]{.mark}

-   [anthologiagraeca.org](https://anthologiagraeca.org/)

> The project Anthologia graeca aims to gather as much information and data as possible on the Greek Anthology and to produce new ones, thus continuing the anthological enterprise. The platform includes, among other things, different versions of the Greek text, various translations into different languages, notes, commentaries, information on the authors, images of the codex (the palatinus graecus 23), keywords, places cited, etc. This project is based on a **participatory science approach** and encourages participation by non-specialists, particularly beginners in ancient Greek. Many Italian high school students took part in transcribing and translating the text.

-   [Darwin Correspondence Project](https://www.darwinproject.ac.uk/)

> The platform provides the edition of more than 15 000 documents, consisting of letters sent by and received of Charles Darwin and articles, and contextualizing commentaries dedicated to the correspondents and to thematic dossiers. While the platform aims to reach a broader audience it offers visualizations, teaching material for school and university context and further resources (audio, video and interactive modules).

-   [Digitale Historisch-kritische Gesamtausgabe der Werke und Briefe von Jeremias Gotthelf](https://gotthelf-digital.ch/)

> Following a hybrid publication concept the project of the historical-critical edition of Jeremias Gotthelf's works and correspondence offers in its digital presentation different views on the edited documents and rich internal links and links to external resources. In order to meet the requirements for a historical-critical edition it offers in addition to proper commentary views philological views in a text-genetical manner that allow an interactive use and insights into the writing processes. To reach not only a scientific audience the digital presentation was conceptualized in cooperation with experts of the field of human-centered design and using a social science methodology (interviews, validation) to respect the interests of different user groups.

-   [Les herbiers de Rousseau](https://lesherbiersderousseau.org/)

> This platform provides access to all of the Jean-Jacques Rousseau\'s herbariums known to date (2023). Each collection is enriched with botanical, historical, and codicological data produced by a team of specialists from many fields (philologists, botanists, computer engineers) who worked on very complicated non-textual artifacts: herbarium in codex, in boxes, which led the team to propose a categorization and a visualisation not only of specimen, but also of supports and \"containers\".

-   QED - sources and edition of the Max Weber Foundation

> QED is the portal for the publication of digital sources and editions for MWS. The represented topics reflect the international, cross-epochal and interdisciplinary research of its institutes: for now edition projects are "Gallica Pontificia" by DHI Paris (https://doi.org/10.58137/001-2023-0) about medieval regesta; "Dengbêj Gazîn: Songs of a Kurdish Woman" by Orient Institute Istanbul (https://doi.org/10.58137/003-2025-1) about kurdish oral hertitage; "Soviets Survivors" by the Max Weber Network Eastern Europe (work in progress: <https://qed.perspectivia.net/soviet-survivors/)> about the  interviews with Soviet survivors of the German occupation; "Languages of Diplomacy" by MWN Eastern Europe about diplomatic documents and correspondence in the 18th century (work in progress). The platform has a strong sustainability approach for simple scholarly digital edition projects. It is part of the institutional MWS research infrastructure.

-- Tacitus On Line

> This website gathers the most important commentaries of Tacitus by early modern historians including Justus Lipsius. The project is intended to propose a web laboratory, with full access to sources in XML-TEI format, complex queries functionnalities and bibliographic features. As some other digital editions produced by the ELAN team, it is displayed online with continuous integration from a gitlab.

See also in the bibliography ( ➚ **7. 4.**) the list of editions used as examples in the different chapters of the handbook.

## Resources

### Educational resources

-   Automatic Text Recognition (ATR)-Tutorial: https://www.adfontes.uzh.ch/tutorium/atr/atr-models (Dändliker, Lorenz; Bitterli Laura; Ströbel, Phillip: Ad fontes, Automated Text Recognition -- Making (Handwritten) Documents Accessible, CC-BY, 2025.

> In this tutorial the functionality and operation of ATR is explained (chapter 4)

-   W3Schools XML Tutorial: https://www.w3schools.com/xml/

> Helps you to learn how to write in XML (chapter 4)

-   Text Encoding Initiative (TEI) by Example: https://www.teibyexample.org/exist/examples/

> Helps you to apply the basics of the TEI to simple use cases (chapter 4)

-   DARIAH-DE TEI Tutorial: <https://de.dariah.eu/en/tei-tutorial>

> Helps you learn specifics part of the TEI with focus on primary sources (chapter 4)

-   #dariahTeach course "Digital Scholarly Editions: Manuscripts, Texts and TEI Encoding": https://teach.dariah.eu/course/view.php?id=32

> Helps you learn how to create critical editions with XML, the TEI, and XSLT (chapter 4)

-   TEIPublisher from scratch: https://github.com/eeditiones/workshop/

> A repository containing learning materials about TEI Publisher and related technologies (XPath and XQuery), where you can find data and assignments prepared for different events

-   Introduction to linked data (European commission-open data support): https://data.europa.eu/sites/default/files/d2.1.2_training_module_1.2_introduction_to_linked_data_en_edp.pdf

> Helps you gain an understanding of linked data, open data, the difference between the two, how to publish linked data and the economic and social aspects of linked data

-   Leaf Writer Tutorial: https://www.leaf-vre.org/docs/training/tutorials/leaf-writer-basics-tutorial or https://leaf-writer.leaf-vre.org/

> Helps you learn how to create and edit TEI XML files on the open webservice Leaf Writer. Leaf Writer is a community project, created and maintained in Canada.

-   Programming Historian: <https://programminghistorian.org/en/lessons/>

> Tutorials about a lot of relevant topics in the Programming Historian website (some lessons are translated in French and Spanish).

### Catalogues of DSEs

-   AGATE. <https://agate.academy/>.

> Research information system of the German union of Academies acting as funding body for long term research projects, very often in form of Editions. Curated. Updated on a regular basis.

-   Peter Andorfer / Greta Franzini: Catalogue Digital Editions. 2025. <https://dig-ed-cat.acdh.oeaw.ac.at/> \[CDE\]

> The Catalogue was founded by Greta Franzini. States whether an edition is also present in the CDSE.

-   A catalog of Digital Scholarly Editions. Edited by Patrick Sahle et al. 2020ff. https://www.digitale-edition.de/. \[CDSE\]

> A catalog initiated by Patrick Sahle. First ever catalogue of digital editions dating back to the late 1990s. Curated. Updated on a regular basis.

-   Datenbank über Editionsprojekte in den Geschichtswissenschaften. 2014ff. <https://www.infoclio.ch/de/edition-projects>

> Founded in 2014, regularly refreshed, this catalogue focusses on editorical projects created in Switzerland in the field of historical sciences.

-   The Text+ Registry. https://registry.text-plus.org/edition/landing?lang=en.

> An open meta-catalog for printed, hybrid and born-digital editions. Imports catalogues (e.g. Sahle, Franzini & AGATE, RSD), curates and harmonises metadata to rich resource descriptions of editions to improve interoperability and findability of editions. curated. Updated on a regular basis.

-   e-editiones Project Registry. https://www.e-editiones.org/map/

> A map of the digital editions published with a TEI Publisher instance

### Catalogues of Tools

-   Chiara Martignano. «DSETools (Catalogue of Software Tools for Digital Scholarly Editing)». Zenodo, 12 January 2026. <https://doi.org/10.5281/zenodo.18211572>.

> A collection of tools for the various steps of digital philology with examples from existing digital editions (chapter 4)

-   Research Software Directory (RSD) for Editions Tools. https://research-software.cceh.uni-koeln.de/software.

> An instance of RSD to show tools and software useful for SDE. Connected to Text+ Registry. Curated. Updated on a regular basis.

-   Center for digital editions and edition analytics, University of Zürich. https://www.zde.uzh.ch/en/analytics.html

> On this page you will find an overview of selected tools and infrastructures used for the analysis and visualization of text phenomena or for the standardization of data 

-   Pandore Toolbox. https://obtic-gpu1.mesu.sorbonne-universite.fr/pandore/

> Set of modules for automatically performing the most common corpus processing tasks for digital humanities research; processing chains for automating a range of tasks are also available.

-   Fragmentary Texts, Monica Berti. <https://www.fragmentarytexts.org/about/>

> "Methodologies and tools for collecting and representing quotations and text reuses of Classical sources."

-- Several DSE working environments have been designed within the Pôle Document numérique (MRSH Caen) to work with the XML editor : https://mrsh.unicaen.fr/pluridisciplinaire/pole-document-numerique/outils/

> "Methodologies and tools for research tools or catalogues for describing librairies collections in XML EAD and for describing textual objects of DSE in XML TEI ."

## Further Information for degree programs and infrastructures

### Degree programs: Edition philology/science

-   Bern University: Degree program: Editionsphilologie: https://www.philhist.unibe.ch/studium/studienprogramme/master_editionsphilologie/index_ger.html

-   Wuppertal University: Degree program: Dokument- und Editionswissenschaft: <https://edw.uni-wuppertal.de/de/startseite/>

### Infrastructures 

Depending on the country where you work, infrastructures are available **at different levels** to support your work. France is known to be centralised and provides national infrastructures with regional liaisons, while Germany is only starting to build cross-discipline and cross-regional infrastructures and has long been offering mainly support at institutional level, for instance. Additionally, the European Union is striving to leverage EU-wide common repositories like European Open Science Cloud (EOSC) and encourages community-building in the context of so-called ERICs (European Research Infrastructure Consortium) like DARIAH, organized in regional hubs.

There is **no simple answer** to the question of the relevant infrastructure that would apply universally for all DSE projects and for all phases of a DSE projects. But there is certainly around you someone who has the information that will help you take informed decisions. These professionals usually are: librarian, data stewards, in France also research engineers. Ask for these contacts at your institution to get a better understanding of the infrastructures that can best support a DSE in the conception phase (developers team, librarians for access to archives and sources, storage of data), in its use phase (perhaps other developers, engineers, infrastructure for publishing data/publisher), and in the long run, especially in case funding runs out at some point (big infrastructures for long-term storage and archiving, but also developers for maintenance and implementations of new versions for software).

The list below offers a non exhaustive list of infrastructures, functioning at the date of the present version of the handbook, which may give you support (free or at a cost) in data storage, hosting, data management, support or training:

\[Table made by ChatGPT, being checked and updated by a tired human - please feel free to update\]

  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  **Infrastructure**                                                       **Link**                                                     **Country / Scope**      **Keywords**
  ------------------------------------------------------------------------ ------------------------------------------------------------ ------------------------ ----------------------------------------------------------------------------
  OPERAS Research Infrastructure                                           https://operas-eu.org                                        Europe (ERIC)            Scholarly communication, open access publishing, humanities infrastructure

  Zenodo (CERN repository)                                                 https://zenodo.org                                           Europe / Switzerland     Research data repository, DOI assignment, long-term storage

  Huma-Num                                                                 https://documentation.huma-num.fr/                           France                   Digital humanities infrastructure, hosting, data management

  Nakala (Huma-Num repository)                                             https://nakala.fr                                            France                   Research data repository, persistent identifiers, datasets

  Biblissima+                                                              https://www.biblissima.fr                                    France                   Manuscript data infrastructure, medieval sources, digital editions

  Text+ Task-Area Scholarly Editions (NFDI consortium)                     https://text-plus.org/ueber-uns/arbeitsbereiche/editionen/   Germany                  Consulting, Digital Editions, Catalogue

  ACDH-CH (Austrian Centre for Digital Humanities and Cultural Heritage)   https://www.oeaw.ac.at/acdh/what-we-offer                    Austria                  Digital humanities infrastructure, hosting, tools, editions

  DaSCH (Swiss National Data and Service Center for the Humanities)        https://dasch.swiss/services                                 Switzerland              Digital humanities infrastructure, long-term preservation, linked data

  Europeana                                                                https://www.europeana.eu                                     Europe                   Cultural heritage aggregation, training, promotion

  Pelagios / Recogito                                                      https://recogito.pelagios.org                                Europe / International   Annotation tools, linked open data, historical places
  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Funding

The following non-exhaustive list provides starting points for funding opportunities and support programmes:

-   Funding opportunities in the European context (overview): https://staff.ki.se/research-support/research-funding-economy/step-1-grant-application/european-research-funding

-   In France, please look at: https://anr.fr/

-   In Germany, research projects can be funded by institutions, Academies, private and/or semi-public foundations or societies, e.g.: German Research Foundation (Deutsche Forschungsgemeinschaft DFG), Akademienprogramm, Thyssen-Stiftung, Volkswagenstiftung. Note that in Germany, cooperating with libraries or partner institutions can strengthen applications, but some schemes require an independent contribution. It can also be helpful to contact the funding body before submitting to clarify questions.

-   Switzerland: Swiss National Science Foundation (SNF; projects typically last up to four years). At the moment, there are no funding opportunities for new long-term editions. This may change in the future (please check the website of the Schweizerische Akademie der Geistes- und Sozialwissenschaften [SAGW](https://www.sagw.ch/sagw/forschungsinfrastrukturen)).

-   Austria: Austrian Research Foundation (Östereichische Forschungsgemeinschaft, [ÖFG](https://www.oefg.at/))

## Bibliography

Link to the zotero collection:

https://www.zotero.org/groups/6348967/digital_scholarly_editions_booksprint/library

#### Editions used as examples in the different chapters

"Beethovens Werkstatt." Das Projekt Beethovens Werkstatt kombiniert zwei Forschungsansätze -- Genetische Textkritik und Digitale Musikedition -- um kompositorische Prozesse im Œuvre Beethovens zu untersuchen. Accessed April 13, 2026. https://beethovens-werkstatt.de/.

"Bibliothek Der Kirchenväter." Accessed April 13, 2026. https://bkv.unifr.ch/de.

Carraud, Vincent, and Julia Roger. "Corpus Descartes, Édition En Ligne Des Œuvres et de La Correspondance de Descartes." Édition numérique. n.d. XML TEI. Accessed September 9, 2025. <https://www.unicaen.fr/puc/sources/prodescartes/>.

Darwin Correspondence Project. "Darwin Correspondence Project." Accessed April 13, 2026. https://www.darwinproject.ac.uk/.

"Dengbêj Gazîn: Songs of a Kurdish Woman." Accessed April 13, 2026. https://qed.perspectivia.net/gazin/.

"Encyclopédie Méthodique \| ARTFL Encyclopédie." Accessed March 6, 2026. [https://encyclopedie.uchicago.edu/encyclop%C3%A9die-m%C3%A9thodique](https://encyclopedie.uchicago.edu/encyclopédie-méthodique).

Gotthelf Digital -- dHKG. "digitale Historisch-kritische Gesamtausgabe der Werke und Briefe von Jeremias Gotthelf." Accessed April 13, 2026. https://gotthelf-digital.ch/.

"Korrespondenzen Der Frühromantik." Accessed April 13, 2026. https://briefe-der-romantik.de/.

"Nägeli Briefedition." Accessed April 13, 2026. https://naegeli-briefe.ch/home.

"Online Edition of Johann Caspar Lavater's Correspondences." Accessed April 13, 2026. https://www.jclavater-briefwechsel.ch/about.

"République des Lettres - Daten- und Editionsplattform." Accessed April 13, 2026. https://republique-des-lettres.ch/.

#### Literature

"A Guide to the FAIR Principles \| Openscience.Eu." July 7, 2025. https://openscience.eu/article/infrastructure/guide-fair-principles.

Altenhöner, Reinhard, Andreas Berger, Christian Bracht, et al. *DFG Practical Guidelines on Digitisation. Updated Version 2022.* February 16, 2023. https://doi.org/10.5281/ZENODO.7561148.

Andrews, Tara L., and Joris J. van Zundert. *What Are You Trying to Say? The Interface as an Integral Element of Argument*. Vol. 12, edited by Roman Bleier, Martina Bürgermeister, Helmut W. Klug, Frederike Neuber, and Gerlinde Schneider. BoD, 2018. <http://www.uni-koeln.de/>.

Bisson, Marie, Edith Cannet, Anne Goloubkoff, et al. "Modélisation Des Métadonnées En XML-TEI. Pratiques de l'IR Métopes et Du Pôle Document Numérique de La MRSH de Caen." October 2022. https://hal.science/hal-03830903.

Bleier, Roman, Martina Bürgermeister, Helmut W. Klug, Frederike Neuber, and Gerlinde Schneider, eds. *Digital Scholarly Editions as Interfaces*. Schriften Des Instituts Für Dokumentologie Und Editorik 12. BoD, 2018.

Boros, Emanuela, Maud Ehrmann, Matteo Romanello, Sven Najem-Meyer, and Frédéric Kaplan. "Post-Correction of Historical Text Transcripts with Large Language Models: An Exploratory Study." In *Proceedings of the 8th Joint SIGHUM Workshop on Computational Linguistics for Cultural Heritage, Social Sciences, Humanities and Literature (LaTeCH-CLfL 2024)*, edited by Yuri Bizzoni, Stefania Degaetano-Ortlieb, Anna Kazantseva, and Stan Szpakowicz. Association for Computational Linguistics, 2024. https://doi.org/10.18653/v1/2024.latechclfl-1.14.

Burnard, Lou. "On the Hermeneutic Implications of Text Encoding." In *New Media and the Humanities : Research and Applications : Proceedings of the First Seminar, "Computers, Literature and Philology", Edinburgh, 7-9 September 1998*, edited by Domenico Fiormonte and Jonathan Usher. Humanities Computing Unit, University of Oxford, 2001.

Calvo Tello, José, Mathias Göbel, Ubbo Veentjer, Stefan E. Funk, Nanette Rißler-Pipka, and Keli Du. "FAIR Derived Data in TEI and Its Publication in the TextGrid Repository." *Journal of the Text Encoding Initiative* 18 (2024). https://doi.org/10.4000/13llz.

Candela, Gustavo, María Dolores Sáez, MPilar Escobar Esteban, and Manuel Marco-Such. "Reusing Digital Collections from GLAM Institutions." *Journal of Information Science* 48, no. 2 (2022): 251--67. https://doi.org/10.1177/0165551520950246.

Chun, Wendy Hui Kyong, Richard Grusin, Patrick Jagoda, and Rita Raley. "The Dark Side of the Digital Humanities." In *Debates in the Digital Humanities 2016*, edited by Matthew K. Gold and Lauren F. Klein. University of Minnesota Press, 2016. JSTOR. https://doi.org/10.5749/j.ctt1cn6thb.41.

Cugliana, Elisa. *Coding Editions. Computational Approaches to the Editing of Pre-Modern Texts.* March 10, 2023. https://doi.org/10.5281/ZENODO.7715284.

Cummings, James. "A World of Difference: Myths and Misconceptions about the TEI." *Digital Scholarship in the Humanities* 34 (December 2018). https://doi.org/10.1093/llc/fqy071.

Ding, Yi, and Tianyao Shi. "Sustainable LLM Serving: Environmental Implications, Challenges, and Opportunities : Invited Paper." *2024 IEEE 15th International Green and Sustainable Computing Conference (IGSC)*, November 2024, 37--38. https://doi.org/10.1109/IGSC64514.2024.00016.

Driscoll, Matthew James, and Elena Pierazzo. *Digital Scholarly Editing: Theories and Practices*. Open Book Publishers, 2016. https://doi.org/10.11647/obp.0095.

"FAIR Principles." n.d. https://www.go-fair.org/fair-principles/.

Fernández Riva, Gustavo, and Victor Millet. "Der Arme Heinrich - Digital: Transcriptions." With Gustavo Fernández Riva, Victor Millet, Heidelberg University Library, Jakub Šimek, and Dietmar Peschel. heiDATA, 2018. Text/xml. https://doi.org/10.11588/DATA/FNKJ2Y.

Fullerton, Tracy. "Walden, a Game EDU." *Games + Learning + Society Conference Proceedings*, September 18, 2022. https://escholarship.org/uc/item/9tn6053m.

Galleron, Ioana, Marie-Luce Demonet, Cécile Meynard, et al. *Les publications numériques de corpus d'auteurs -- Guide de travail, grille d'analyse et recommandations, consortium CAHIER*. Consortium CAHIER, 2018. <https://cahier.hypotheses.org/guides/les-publications-numeriques-de-corpus-dauteurs>.

GitHub. "LABEX OBVIL." Accessed April 13, 2026. https://github.com/OBVIL.

Götz, Carmen, ed. *Alexander von Humboldt: Tagebücher der Amerikanischen Reise: Von Spanien nach Cumaná*. Springer Berlin Heidelberg, 2022. https://doi.org/10.1007/978-3-662-64274-0.

Greening DH. "Greening DH." Accessed April 13, 2026. https://dhd-greening.github.io/.

"Handbuch Zur Erstellung Einer Digitalen Edition - Beta Version." Accessed December 18, 2025. https://digital-editions.pages.uzh.ch/proto4diged/handbook/.

Henzel, Katrin. "Digitale Genetische Editionen Aus Der Nutzerperspektive." In *Textgenese in Der Digitalen Edition*, edited by Anke Bosse and Walter Fanta. De Gruyter, 2019. https://doi.org/10.1515/9783110575996-005.

Hess, Jan. "Von OCR Und HTR Bis NER Und LLM: Zur (Teil-)Automatisierung Digitaler Editions- Und Transformationsprozesse." *Editio* 38, no. 1 (2024): 147--62. https://doi.org/10.1515/editio-2024-0009.

Hindermann, Maximilian, Sorin Marti, Anthea Alberto, et al. *RISE-UNIBAS/Humanities_data_benchmark*. Zenodo, released March 24, 2026. https://doi.org/10.5281/ZENODO.19204070.

International Research Office of the University of Padua. "Fair Data Management Plan. Guidelines and Annotated Template. Based on the Horizon Europe Data Management Plan Template." September 18, 2024. https://biblio.unipd.it/biblioteca-digitale/per-chi-pubblica/documenti-e-materiali/unipd_dmp-guidelines_18-09-2024_v4-3.pdf.

Jacobsen, Annika, Ricardo De Miranda Azevedo, Nick Juty, et al. "FAIR Principles: Interpretations and Implementation Considerations." *Data Intelligence* 2, nos. 1--2 (2020): 10--29. https://doi.org/10.1162/dint_r_00024.

Jones, Steven, and Neil Fraistat. "The MOO as an Arcade: Minimalism and Interpretive literary Games." *TEXT Technology* 13, no. 2 (2004): 19--26.

Kanerva, Jenna, Cassandra Ledins, Siiri Käpyaho, and Filip Ginter. "OCR Error Post-Correction with LLMs in Historical Documents: No Free Lunches." In *Proceedings of the Third Workshop on Resources and Representations for Under-Resourced Languages and Domains (RESOURCEFUL-2025)*, edited by Špela Arhar Holdt, Nikolai Ilinykh, Barbara Scalvini, Micaella Bruton, Iben Nyholm Debess, and Crina Madalina Tudor. University of Tartu Library, Estonia, 2025. https://aclanthology.org/2025.resourceful-1.8/.

Klug, Helmut W., Selina Galka, and Elisabeth Steiner. *KONDE Weißbuch - Kompetenznetzwerk Digitale Edition*. 2021. https://www.digitale-edition.at/context:konde.

Kuczera, Andreas. "TEI Beyond XML--Digital Scholarly Editions as Provenance Knowledge Graphs." *Graph Technologies in the Humanities---Proceedings 2020, CEUR Workshop Proceedings* 3110 (2020): 101. https://ceur-ws.org/Vol-3110/paper6.pdf.

Lagarias, Antonios. "Colloque CHR 2024 : les LLM (large language models) au service des humanités numériques ?" *Humanités numériques*, no. 11 (July 2025). <https://doi.org/10.4000/1498y>.

Lange, Judith. "Einmal Alles, Bitte!" *Chancen Und Herausforderungen Hybrider Editionen*, editio, vol. 39, no. 1 (2025): 18--33. https://doi.org/10.1515/editio-2025-0002.

Lobis, Ulrich, and Joseph Wang-Kathrein. "Versionierung." In *KONDE Weißbuch*. 2021. hdl.handle.net/11471/562.50.14.

Lukas, Wolfgang, Dana Machwitz, and Bastian Politycki. "Pörtner & Wühr: Spuren Des Original-Ton-Hörspiels Zwischen Wuppertal Und München: Ein Versuch, Textgenese Und Produktionsästhetik Auszustellen." *Editio* 37, no. 1 (2023): 102--21. https://doi.org/10.1515/editio-2023-0007.

O'Sullivan, James, Michael Pidd, Sophie Whittle, Bridgette Wessels, Michael Kurzmeier, and Órla Murphy, eds. *Digital Editing and Publishing in the Twenty-First Century*. 1st ed. Scottish Universities Press, 2025. https://doi.org/10.62637/sup.GHST9020.

Päßler, Ulrich, and Ottmar Ette, eds. *Alexander von Humboldt: Geographie der Pflanzen: Unveröffentlichte Schriften aus dem Nachlass*. J.B. Metzler, 2020. https://doi.org/10.1007/978-3-476-04965-0.

Pierazzo, Elena. "Digital Documentary Editions and the Others." *Scholarly Editing* 35 (2014). https://scholarlyediting.org/2014/essays/essay.pierazzo.html.

Pollin, Christopher, Franz Fischer, Patrick Sahle, Martina Scholger, and Georg Vogeler. "When It Was 2024 -- Generative AI in the Field of Digital Scholarly Editions." *Zeitschrift Für Digitale Geisteswissenschaften* 10 (2025). https://doi.org/10.17175/2025_008.

Re3data.Org. "CMO Editionen und Quellen-Katalog." Preprint, Re3data.org - Registry of Research Data Repositories, 2019. https://doi.org/10.17616/R31NJMJV.

Reiling, Jesko, and Sharon Rom. "Digitale Editionen als Forschungsservice: Pilotprojekt der ZB Zürich zu neuen Formen der digitalen Bestandspräsentation." *o-bib. Das offene Bibliotheksjournal / Herausgeber VDB* 12, no. 4 (2025): 1--5. https://doi.org/10.5282/o-bib/6184.

Ries, Thorsten, Tara Andrews, Lisa Rosendahl, et al. *Critical AI in Der Digitalen Editorik*. February 26, 2025. https://doi.org/10.5281/ZENODO.14943125.

Rillig, Matthias C., Marlene Ågerstrand, Mohan Bi, Kenneth A. Gould, and Uli Sauerland. "Risks and Benefits of Large Language Models for the Environment." *Environmental Science & Technology* 57, no. 9 (2023): 3464--66. https://doi.org/10.1021/acs.est.3c01106.

Roeder, Torsten, and Patrick Sahle. "Architekturen. Überblick über Software für Editionen." Winter School Digitale Editionen, 02.-01.03 2019. https://www.i-d-e.de/wp-content/uploads/2019/11/08_Architekturen.pdf.

Sahle, Patrick. *Digitale Editionsformen, Zum Umgang Mit Der Überlieferung Unter Den Bedingungen Des Medienwandels, 3 Bände*. n.d. https://www.i-d-e.de/publikationen/schriften/s7-9-digitale-editionsformen/.

Sahle, Patrick. "What Is a Scholarly Digital Edition?" In *Digital Scholarly Editing*, edited by Matthew James Driscoll and Elena Pierazzo. Open Book Publisher, n.d. https://books.openedition.org/obp/3397.

Saklofske, Jon, Nina Belojevic, Alex Christie, Sonja Sapach, John Simpson, and The INKE Research Team. "Gaming the Edition: Modelling Scholarly Editions through Videogame Frameworks." *Digital Literary Studies* 1, no. 1 (2016). https://doi.org/10.18113/P8dls1159703.

Schonhardt, Michael. "Do One Thing and Do It Well. Vier Prinzipien einer digitalen Editionspraxis im Spannungsfeld zwischen fachlichen Standards und Deep Learning." *Digitales Edieren gestern, heute und morgen* Sonderband 7 (2025). https://doi.org/10.17175/SB007_005.

Smithies, James. "The Dark Side of DH." In *The Bloomsbury Handbook to the Digital Humanities*, edited by James O'Sullivan. Digital Humanities. Bloomsbury Academic, 2023.

Spadini, Elena. "Scholarly Editing and the Semantic Web." In *Quantitative Und Qualitative Analyseperspektiven Für Eine Digitale Briefforschung*, edited by Aline Deicke and Jochen Strobel. De Gruyter, 2025. https://doi.org/doi:10.1515/9783111675732-003.

Team, The Endings Project. "The Endings Project: Principles \| Principes." Accessed April 13, 2026. https://endings.uvic.ca/\[page file name will be inserted here\].

Thomas, Alan, Robert Gaizauskas, and Haiping Lu. "Leveraging LLMs for Post-OCR Correction of Historical Newspapers." In *Proceedings of the Third Workshop on Language Technologies for Historical and Ancient Languages (LT4HALA) @ LREC-COLING-2024*, edited by Rachele Sprugnoli and Marco Passarotti. ELRA and ICCL, 2024. https://aclanthology.org/2024.lt4hala-1.14/.

Van Mierlo, Wim. *Scholarly Editing in Perspective*. 1st ed. Cambridge University Press, 2025. https://doi.org/10.1017/9781009183772.

Vogeler, Georg. "Die konzentrische Edition. Auswertungspotentiale von digitaler Tiefenerschließung, Proto-Editionen, künstlichen Editionen und digitalen Volleditionen der Reichshofratsprotokolle." In *Der kaiserliche Reichshofrat*, 1st ed., edited by Ulrich Rasche and Tobias Schenk. Böhlau Verlag Köln, 2025. https://doi.org/10.7788/9783412530563.489.

Wilkinson, Mark D., Michel Dumontier, IJsbrand Jan Aalbersberg, et al. "The FAIR Guiding Principles for Scientific Data Management and Stewardship." *Scientific Data* 3, no. 1 (2016): 160018. https://doi.org/10.1038/sdata.2016.18.

Zimmermann von, Christian. "Textphilologie -- Kommentar -- Usability. Eine Philologische Bilanz Zum Übergang von Der Buchedition Zur Digitalen Edition." *Archiv Für Das Studium Der Neueren Sprachen Und Literaturen* 262, no. 1 (2025): 1--25.

##  {#section .unnumbered}

## Quick access by keywords

  -----------------------------------------------------------------------
  access
  -----------------------------------------------------------------------
  adaptability

  AI (Artificial Intelligence)

  authority files

  born digital

  CARE principles

  catalogues

  citability

  CMS (Content Management System)

  collaborators

  collaboration

  community

  computer

  computer language

  critical representation

  curation-driven approach

  data modelling

  data reuse

  database

  digital scholarly edition

  digital editing practices

  digitisation

  DMP (Data Management Plan)

  documentation

  document

  editorial approaches

  editorialization

  engineers

  environmental impact

  ethics

  facsimile

  FAIR principles (Findable, Accessible, Interoperable, Reusable)

  format

  funding

  git

  GLAMs (Galleries, Libraries, Archives and Museums)

  granularity

  images

  inclusion

  institutions

  interface

  interoperability

  key characteristics

  languages (programming languages / markup langages)

  licenses

  licensing

  literature

  LLM (Large Language Model)

  maintenance

  metadata

  methodology

  modelling

  non textual objects

  ontology

  open

  persistent identifier

  planning

  primary sources

  project design

  project planning

  proprietary

  publishing

  repository

  research-driven approach

  research ethics

  research question

  retro-digitisation

  reusability

  review

  schedule

  sources

  source selection

  stability

  standards

  state of the art

  support

  sustainability

  tasks

  teaching

  team composition

  text encoding

  text recognition

  training

  typology of editions

  transcription

  unicode

  usability

  user experience

  versioning

  visualisation

  word processor

  workflow

  WYSIWYG 

  xml-schema

  XSLT (eXtensible Stylesheet Language Transformations)
  -----------------------------------------------------------------------

## DSE evaluation criteria

This section draws on: *Criteria for Reviewing Scholarly Digital Editions*, version 1.1, by Patrick Sahle; in collaboration with Georg Vogeler and the members of the IDE; Version 1.1, June 2014 (Version 1.0, September 2012 -- January 2014; German version 1.1: http://www.i-d-e.de/publikationen/weitereschriften/kriterien-version-1-1/), including major contributions to the English version by: Misha Broughton, James Cummings, Franz Fischer, Philipp Steinkrüger, Walter Scholger.

The following evaluation criteria were conceived to assess DSEs.

Digital Scholarly Editions, like any online resource, are susceptible of improvement. They can be updated, edited, expanded (or reduced) at any time. As a consequence, the evaluation of a Digital Scholarly Edition comes with a time stamp and version identification, and it accounts for a progress margin within the given material conditions in which the edition is conceived and implemented.

### State of the art[]{.mark}

-   What does the DSE integrate from earlier editorial work (e.g., print editions or other digital resources) and how does it contribute to the further enrichment of this prior work?

-   Does the DSE state its specificities compared to already existing ones, and account for the way in which it integrates recent technological advances?

### [Interface]{.mark}

-   Is the user interface of the DSE clearly arranged (browsing, search function, indices, image quality)? Is the user at any time made aware of what is currently displayed and how other content can be accessed?

<!-- -->

-   How inclusive is the interface? (see the [documentation of the Web Accessibility Initiative](https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/) for more information)

-   Does the interface document the underlying methodology (technical documentation, editorial guidelines)?

-   Does the interface show exactly what the editor planned for it to display?

-   Does the interface include a feedback button or an easy contact form?

<!-- -->

-   Does the DSE contain additional features like visualisations? Are they useful?

<!-- -->

-   Is a low-resource version of the interface available? []{.mark}

### Method & content

-   Is the production of the DSE laid out clearly (where applicable: and of its different versions)?

-   Is laid out clearly what the DSE publishes (quality and quantity of edited artifacts, full text, scholarly and editorial enrichments)? Is relevant content missing (if so, is that justified)?

-   Are the editorial choices and methods clear, justified and applied properly?

-   Is the data model laid out clearly, justified and implemented properly? Are the relevant standards followed (if not, is this justified)? Are the technological choices justified (e.g., balance between the realistic work conditions in the project and best practices)?

-   Are the quality control measures used in the production of the DSE presented? Are they sufficient?

-   To what extent does the DSE successfully achieve its goals?[]{.mark}

### Accessibility and reusability

-   Is the DSE clearly identified (responsible editors, date of publication (if relevant, of versions), address (DOI, URN or PURL)) and this information easy to access on the DSE interface? Are citation guidelines provided?

-   Are the principles of selection or sampling of the edited documents clear and understandable?

-   Are technical interfaces like OAI-PMH, REST, APIs provided to facilitate data reuse in other contexts?

-   Is long term availability and access ensured, how and for which part of the DSE?

-   Are there alternative formats available (eBooks, mobile devices,\...)?

-   Is sufficient information on licenses, e.g. reuse conditions, regarding the different information layers provided (basic text, images, metadata) and their versions?

####  {#section-1 .unnumbered}
